language: ruby
rvm:
 - 2.2

services:
  - postgresql

before_script:
  - cp config/database.travis.yml config/database.yml
   - psql -c "CREATE USER sow WITH PASSWORD 'password';" -U postgres
  - psql -c 'create database jobnexttome_test;' -U postgres